from functools import reduce, partial
import numpy as np

# 목차
>## 1. 스칼라
## 2. 벡터
## 3. 행렬
## 4. numpy를 이용한 배열연산

----------_

# 선형 대수
- 벡터 공간을 다루는 수학의 한 분야
- 스칼라 (scalar), 벡터 (vector), 행렬 (matrix) 세 가지 유형을 가진다.


## 1. 스칼라 (scalar)
>- 하나의 숫자만으로 이루어진 데이터
- 보통 $x$와 같이 소문자로 표기함

## 2. 벡터
>- 벡터끼리 더하거나 상수와 곱해지면 새로운 벡터를 생성하는 개념적인 도구.
- 일반적으로 1차원 배열을 벡터라고 한다.
- 하나의 벡터를 이루는 데이터의 개수를 차원(dimension)라고 한다.
- 예시
    - 사람을 표현하는 벡터
        - [키, 몸무게, 나이] 인 3차원 벡터
    - 성적 벡터
        - [시험 1 점수, 시험 2 점수, 시험 3 점수, 시험 4 점수] 인 4차원 벡터



## (1) 파이썬에서의 벡터
>- 가장 쉽게 표현하는 방법은 list로 표현하는 방법이다.

In [3]:
height_weight_age = [
    180, # 키
    73,  # 몸무게
    40   # 나이
]

## (2) 파이썬 list는 벡터 연산이 가능한가?
>- 파이썬의 list는 실제로 벡터가 아니므로, 벡터 연산이 불가능하다.
    - list가 벡터 연산이 되도록 하기 위해서는 따로 작업을 해줘야한다.
- 벡터 연산 ?
    - 각 벡터 상에서 같은 위치에 있는 성분끼리 연산하는 것. ( element-wise 연산 )
    - ex. [1, 2] + [2, 1] = [1 + 2, 2 + 1]
    - 두 벡터의 길이가 다르다면 연산이 불가능하다.

## (3) 벡터 연산
### 벡터 덧셈
> - 벡터 덧셈은 zip을 사용해서 두 벡터를 묶은 뒤, 두 배열의 각 성분끼리 더하는 list comprehension을 적용한다.

In [2]:
def vector_add(v, w):
    """각 성분끼리 더한다."""
    return [v_i + w_i for v_i, w_i in zip(v, w)]

In [3]:
vector_add([1, 2, 3], [2, 3, 4])

[3, 5, 7]

In [ ]:
############################# 스터디원 코드 #############################





In [8]:
def vector_subtract(v, w):
    """각 성분끼리 뺀다."""
    return [v_i - w_i for v_i, w_i in zip(v, w)]

In [9]:
def vector_sum(vectors):
    """모든 벡터의 각 성분들끼리 더한다."""
    result = vectors[0]
    for vector in vectors[1:]:
        result = vector_add(result, vector)
    return result

In [ ]:
############################# 스터디원 코드 #############################





In [10]:
vector_sum([[1, 2, 3], [1, 2, 3]])

[2, 4, 6]

In [132]:
## reduce를 이용하는 방법

def vector_sum(vectors):
    from functools import reduce
    return reduce(vector_add, vectors)

In [12]:
vector_sum([[1, 2, 3], [1, 2, 3]])

[2, 4, 6]

In [13]:
## partial를 이용하는 방법

vector_sum = partial(reduce, vector_add)

In [14]:
vector_sum([[1, 2, 3], [1, 2, 3]])

[2, 4, 6]

### 스칼라 곱

In [15]:
def scalar_multiply(c, v):
    """c는 숫자, v는 벡터"""
    return [c * v_i for v_i in v]

In [16]:
scalar_multiply(5, [1, 2, 3])

[5, 10, 15]

In [ ]:
############################# 스터디원 코드 #############################




### 벡터 평균

In [32]:
def vector_mean(vectors):
    """i번째 성분이 입력된 벡터의 i번째 성분의 평균을
    의미하는 벡터를 계산해준다."""
    n = len(vectors)
    return scalar_multiply(1/n, vector_sum(vectors))

In [33]:
vector_mean([[1, 2, 3], [2, 3, 4]])

[1.5, 2.5, 3.5]

In [ ]:
############################# 스터디원 코드 #############################





### 벡터 내적
> - 내적은 벡터 A가 벡터 B 방향으로 얼마나 멀리 뻗어나가는지를 나타낸다.
- 벡터 A, B에 대하여 $A   \bullet B   =  ||A||_2 ||B||_2 \cos{\theta}$
    - 벡터 크기와 두 벡터 사잇각의 곱으로 정의한다.
    - A와 B가 직교하면 ( = $\cos{90}$),  $A   \bullet B = 0$ 이 된다.



$\begin{matrix} [1 & 2 & 3] \end{matrix} \bullet  \begin{matrix} 2 \\ 3 \\ 4 \end{matrix}$

In [43]:
## zip을 사용해서 두 벡터를 묶은 뒤, 두 배열의 각 성분끼리 곱하는 list comprehension을 적용하고, 마지막 결과를 모두 더해준다.

def dot(v, w):
    """v_1*w_1 + v_2*w_2 + ..."""
    return sum(v_i * w_i for v_i, w_i in zip(v, w))

In [44]:
dot([1, 2, 3], [2, 3, 4])

20

In [ ]:
############################# 스터디원 코드 #############################





> 내적의 개념을 사용하면, 각 성분의 제곱 값의 합을 쉽게 구할 수 있다.

In [114]:
def sum_of_squares(v):
    """v_1*v_1 + v_2*v_2 + ... + v_n*v_n"""
    return dot(v, v)

In [ ]:
############################# 스터디원 코드 #############################





### 벡터 크기
> - 벡터 크기 : $||v||_2 = \sqrt{v^Tv} = \sqrt{v_1^2 + v_2^2 + v_3^2 + ... + v_n^2} $
    - $\cos0 = 1$

In [134]:
def magnitude(v):
    import math
    return math.sqrt(sum_of_squares(v))

In [146]:
magnitude([1, 2, 3])

3.7416573867739413

### 두 벡터 간의 거리

> - 유클리드 거리
- |$\sqrt{(v_1 - w_1)^2 +  ...  + (v_n - w_n)^2} $

In [118]:
## 두 벡터의 각각의 요소들을 빼주는 vector_subtract와 각 요소들의 제곱합을 계산해주는 sum_of_squares를 이용한다.

def squared_distance(v, w):
    """(v_1-w_1)**2 + ... + (v_n - w_n)**2"""
    return sum_of_squares(vector_subtract(v, w))

In [119]:
## math.sqrt를 이용해서 root를 씌어준다.

def distance(v, w):
    import math
    return math.sqrt(squared_distance(v, w))

In [120]:
def distance(v, w):
    return magnitude(vector_subtract(v, w))

In [ ]:
############################# 스터디원 코드 #############################





## 3. 행렬

> - 행렬 : 2차원 배열
    - 3차원 이상 배열은 텐서(tensor)라고 함
- list의 list로 표현할 수 있다.

In [10]:
## 행렬을 list로 표현

A = [[1, 2, 3], 
     [4, 5, 6]]

B = [[1, 2], 
     [3, 4],
     [5, 6]]

In [122]:
## 행렬의 shape를 확인하는 함수 (n, m)

def shape(A):
    num_rows = len(A)
    num_cols = len(A[0]) if A else 0 ## A의 첫번째 행의 element의 갯수
    return num_rows, num_cols

In [123]:
shape(A)

(2, 3)

In [ ]:
############################# 스터디원 코드 #############################





In [124]:
## 행렬의 i번째 행만 가져오는 함수

def get_row(A, i):
    return A[i]

In [125]:
## 행렬의 j번째 열만 가져오는 함수

def get_columns(A, j):
    return [A_i[j] for A_i in A]

In [126]:
get_row(A, 0)

[4, 5, 6]

In [127]:
get_columns(A, 0)

[1, 4]

In [ ]:
############################# 스터디원 코드 #############################





In [128]:
## 행렬의 i번째 행과 j번째 열이 어떠한 규칙을 가지는 행렬을 만드는 함수

def make_matrix(num_rows, num_cols, entry_fn):
    """(i, j)번째 원소가 entry_fn(i, j)인 
    num_rows x num_cols list를 반환"""
    return [[entry_fn(i, j) 
             for j in range(num_cols)]
             for i in range(num_rows)]

In [129]:
## 대각선 상에 위치한 원소는 1, 나머지는 0으로 만드는 함수

def is_diagonal(i, j):
    """대각선의 원소는 1, 나머지 원소는 0"""
    return 1 if i == j else 0


In [130]:
identity_matrix = make_matrix(5, 5, is_diagonal)

In [131]:
## identity matrix는 어떠한 행렬과도 곱하여도 곱해진 행렬 자신으로 나오게된다.

identity_matrix

[[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]

## 4. numpy 를 활용한 배열 연산
- numpy (넘파이)
    - C와 fotran으로 짜여진 파이썬 배열연산 패키지 (매우 빠름)
    - 모든 머신러닝, 딥러닝 알고리즘에 활용되고 있고, numpy 이후부터 python이 과학계산에 널리 사용되었음.

In [11]:
# array creation

a_arr = np.array([1, 2, 3])
b_arr = np.array([2, 3, 4])

a_list = [1, 2, 3]
b_list = [2, 3, 4]

In [12]:
## 더하기 연산 속도 비교

%timeit a_arr + b_arr

The slowest run took 145.42 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 557 ns per loop


In [13]:
%timeit vector_add(a_list, b_list)

1000000 loops, best of 3: 1.57 µs per loop


### (1) 벡터

In [14]:
## numpy array 생성

a_arr = np.array([1, 2, 3]) # 꼭 list형태가 아니어도 된다.
b_arr = np.array([2, 3, 4])

In [139]:
## 덧셈

a_arr + b_arr

array([3, 5, 7])

In [140]:
## 뺄셈

a_arr - b_arr

array([-1, -1, -1])

In [141]:
## 곱셈 (내적이 아님)

a_arr * b_arr

array([ 2,  6, 12])

In [ ]:
############################# 스터디원 코드 #############################





In [142]:
## 내적 1

a_arr.dot(b_arr)

20

In [144]:
## 내적 2

np.dot(a_arr,b_arr)

20

In [ ]:
############################# 스터디원 코드 #############################





In [145]:
## 벡터 크기 연산 

np.linalg.norm(a_arr)

3.7416573867739413

In [148]:
## 거리 (실제로는 이렇게 연산하지 않고 scipy 패키지를 사용함)

np.linalg.norm(a_arr-b_arr)

1.7320508075688772

In [ ]:
############################# 스터디원 코드 #############################





### (2) 행렬

In [15]:
matrix_a = np.array([[1, 2, 3], [2, 3, 4]])
matrix_b = np.array([[10, 20, 30], [20, 30, 40]])

In [28]:
## 행렬 shape

matrix_a.shape

In [17]:
## 행렬 slicing
## 행 선택

matrix_a[1]

array([2, 3, 4])

In [18]:
matrix_a

array([[1, 2, 3],
       [2, 3, 4]])

In [170]:
## 2행의 2번째 열까지

matrix_a[1, :2]

array([2, 3])

In [24]:
## 모든 행의 2번째 열까지
matrix_a[:, :2]

array([[1, 2],
       [2, 3]])

In [172]:
## 전치 행렬

matrix_a.T

array([[1, 2],
       [2, 3],
       [3, 4]])

In [174]:
## 행렬 내적

np.dot(matrix_a, matrix_b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [30]:
matrix_a.shape

(2, 3)

In [31]:
matrix_b.shape

(2, 3)

In [36]:
matrix_a.T.shape

(3, 2)

In [37]:
matrix_b.shape

(2, 3)

In [175]:
## 행렬의 내적을 위해서는 내적이 가능한 shape으로 바꾸어 주어야된다.

np.dot(matrix_a.T, matrix_b)

array([[ 50,  80, 110],
       [ 80, 130, 180],
       [110, 180, 250]])

In [38]:
a_arr.shape

(3,)

In [ ]:
### 스터디원 코드

np.dot(matrix_a.T, matrix_b)

# 보충자료
> - numpy tutorial
    - https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
-  Matlab 사용자를 위한 numpy
    - https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html
- numpy tutorial 한글버전
    - python 2.7로 작성되어있어서 python3.x 에서는 작동하지 않는 코드도 있음.
    - http://aikorea.org/cs231n/python-numpy-tutorial/